### PR TITLE
rescrape afltables historical data

### PR DESCRIPTION
**Pull request by peteowen1**
scraped all historical afltables data to fix the issue:
https://github.com/jimmyday12/fitzRoy/issues/214

only afldata and player_ids changed by running the rescrape

### CODE REVIEW

**Comment by peteowen1** [comment]
actually - wait on this - seems to be some issues with id = 0

**Comment by peteowen1** [comment]
Ok so realised fetch_player_stats_afltables() doesn't work well pre-2021 since IDs are fetched from https://[afltables.com/afl/stats/2021_stats.txt](https://afltables.com/afl/stats/XXXX_stats.txt) which only goes as far back as 2021

Where do the IDs before 2021 even come from? I see there's a df pulled from here
git_url <- "https://raw.githubusercontent.com/jimmyday12/fitzroy_data/main/data-raw/afl_tables_playerstats/player_ids.csv"
but not really sure how that gets built

**Comment by jimmyday12** [comment]
That was a once off provided by Paul at AFL tables. That data isn't available on the site, and the endpoint he temporarily gave us at the time no longer works

**Comment by peteowen1** [comment]
Ahhhh okay - ignore this pull request then as it rewrites the id table (as it does the weekly update script)
Fix will have to be done another way

**Pull request closed without merging**
