### PR TITLE
Afltables fix

### PR DESCRIPTION
**Pull request by peteowen1**
when combined with the fitzRoy merge
https://github.com/jimmyday12/fitzRoy/pull/223
This fixes the following issues:

https://github.com/jimmyday12/fitzRoy/issues/78
https://github.com/jimmyday12/fitzRoy/issues/82
https://github.com/jimmyday12/fitzRoy/issues/136
https://github.com/jimmyday12/fitzRoy/issues/155
https://github.com/jimmyday12/fitzRoy/issues/171 (this is same request as 155)
https://github.com/jimmyday12/fitzRoy/issues/170
https://github.com/jimmyday12/fitzRoy/issues/182
https://github.com/jimmyday12/fitzRoy/issues/214

### CODE REVIEW

**Comment by jimmyday12** [comment]
Having trouble merging this one. I suspect we may need to get https://github.com/jimmyday12/fitzRoy/pull/223 merged first, then potentially run the re-scrape on the main branch. Github isn't liking the conflicts between the RDA and RDS files

**Comment by peteowen1** [comment]
Yeah was curious how it would handle merging the datasets.
But yeah I like the idea of just getting https://github.com/jimmyday12/fitzRoy/pull/223 through and then you can run the re-scrape on main!

**Comment by jimmyday12** [comment]
I've just pushed an update with 'rescrape' set to TRUE and it's running as a Github Action so will see how it goes

**Comment by jimmyday12** [comment]
I've just split the weekly script into two and setup two different github actions to run through them. 

- Fetch AFL Tables weekly takes about 6 mins to run and updates the ID's etc https://github.com/jimmyday12/fitzroy_data/actions/workflows/afltables_scraper.yaml
- Fetch Footywire weekly re-scrapes the entire history of footywire games and takes about 3 hours to run. I may set this to run less regularly but currently also weekly. https://github.com/jimmyday12/fitzroy_data/actions/workflows/footywire_scraper.yaml

**Comment by peteowen1** [comment]
Sweet - Can have a look into the footywire stuff to see if it can be sped up if you want?
First thing I noticed straight away is that it takes 3 seconds to scrape a match and 2 seconds of that is Sys.sleep(2), so could be down to an hour without that.
I assume that's for polite scraping and/or to avoid rate limits? 
In which case fair - but maybe don't need to do a full rescrape every time if that's the case?

**Comment by jimmyday12** [comment]
That'd be awesome. I'll be super honest, I don't remember why that was put in. This would have been one of the first functions I wrote for fitzRoy while still a pretty raw R developer, so I suspect it can be heavily optimised in many ways.

I suspect it was me being pretty conservative early days and wanting to be polite. I think we could likely remove it and just add a user_agent reference to `github.com/jimmyday12`

**Comment by jimmyday12** [comment]
Just also noting here - I've made a commit with a new folder called `data-raw-2`. I'm planning to just use the new scripts to write only the data files we need in fitzRoy to this folder and then update fitzRoy functions to use those files rather than the existing ones. I haven't updated fitzRoy yet, so you'll see the new scripts write to both locations. 

No changes needed but just pointing out the plan of attack here

**Pull request closed without merging**
